modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MPL-2.0"
issueTrackerURL="https://github.com/nocpiun/opanel/issues"
[[mods]]
modId="opanel"
version="${mod_version}"
displayName="OPanel"
displayURL="https://opanel.cn"
logoFile="icon.png"
authors="NriotHrreion"
description='''
A Minecraft server management panel
'''

[[dependencies.opanel]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.opanel]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"