[package]
name = "opanel-pumpkin"
version = "0.1.0"
edition = "2024"
description = "A Minecraft server management panel"
authors = ["NriotHrreion"]

[lib]
path = "pumpkin/lib.rs"
crate-type = ["cdylib"]

[dependencies]
pumpkin = { git = "https://github.com/Pumpkin-MC/Pumpkin.git", rev = "c31eb836164038011dc757729800971e838458e7", package = "pumpkin" }
pumpkin-api-macros = { git = "https://github.com/Pumpkin-MC/Pumpkin.git", rev = "c31eb836164038011dc757729800971e838458e7", package = "pumpkin-api-macros" }
tokio = "1"
tracing = "0.1"
