# https://opanel.cn/docs/configuration

accessKey: ""
salt: ""
webServerHost: "0.0.0.0"
webServerPort: 3000
mcdrSocketPort: 25576
mapPrerenderConcurrent: 4
monitorSnapshotInterval: 1000
serverRestartDelay: 10
cookieSecure: false
proxyHeaders: false
oidcEnabled: false
oidcDiscoveryUrl: ""
oidcClientId: ""
oidcClientSecret: ""
oidcDisplayName: "OIDC"
autoCheckPluginUpdates: true
pluginUpdateCheckInterval: 43200
autoApplyPluginUpdates: false
pluginUpdateRestartStrategy: "defer"
curseForgeApiKey: ""
