modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="opanel"
version="${mod_version}"
displayName="OPanel"
description='''
A web-based server management panel for Minecraft servers
'''
authors="CubeWhy, Contributors"
credits="Thanks to all contributors"
logoFile="opanel.png"
displayURL="https://github.com/CubeWhyMC/OPanel"
updateJSONURL=""

[[dependencies.opanel]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="SERVER"

[[dependencies.opanel]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="SERVER"