plugins {
    id 'java-library'
}

base {
    archivesName = "bukkit-helper"
}

repositories {
    mavenCentral()
    maven {
        name = "spigotmc"
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }
    maven {
        name = "CodeMC"
        url = uri("https://repo.codemc.io/repository/maven-public/")
    }
    maven {
        name = "mojang"
        url = uri("https://libraries.minecraft.net")
    }
}

dependencies {
    compileOnly "org.spigotmc:spigot-api:${common_minecraft_version}-R0.1-SNAPSHOT"
    compileOnly "de.tr7zw:item-nbt-api:2.15.2"
    compileOnly "com.mojang:brigadier:1.0.18"
    compileOnly(project(":core"))
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
