// `plugin_impl` expands lifecycle methods through a second async layer.
#![allow(clippy::async_yields_async)]

use std::sync::Arc;

use pumpkin::plugin::Context;
use pumpkin_api_macros::{plugin_impl, plugin_method};
use tokio::sync::Mutex;
use tracing::info;

use crate::{config::OPanelConfig, opanel::OPanel, web::WebServer};

mod config;
mod event;
mod map;
mod monitor;
mod opanel;
mod task;
mod utils;
mod web;

struct PluginRuntime {
    _opanel: Arc<OPanel>,
    web_server: WebServer,
}

#[plugin_method]
async fn on_load(&self, context: Arc<Context>) -> Result<(), String> {
    let plugin_runtime = Arc::clone(&self.runtime);

    // Native plugins statically link their own Tokio state. Run all lifecycle work on the
    // runtime generated by `plugin_impl` so Tokio I/O can see the correct reactor.
    GLOBAL_RUNTIME
        .spawn(async move {
            context.init_log();

            if plugin_runtime.lock().await.is_some() {
                return Err("OPanel is already loaded".to_string());
            }

            let opanel = Arc::new(OPanel::new(context, OPanelConfig::default()));
            let web_server = WebServer::start(Arc::clone(&opanel))
                .await
                .map_err(|error| format!("failed to start OPanel web server: {error}"))?;

            let mut runtime = plugin_runtime.lock().await;
            if runtime.is_some() {
                drop(runtime);
                web_server.shutdown().await.map_err(|error| {
                    format!("failed to stop duplicate OPanel web server: {error}")
                })?;
                return Err("OPanel is already loaded".to_string());
            }
            *runtime = Some(PluginRuntime {
                _opanel: opanel,
                web_server,
            });

            info!("OPanel loaded");
            Ok(())
        })
        .await
        .map_err(|error| format!("OPanel load task failed: {error}"))?
}

#[plugin_method]
async fn on_unload(&self, _context: Arc<Context>) -> Result<(), String> {
    let plugin_runtime = Arc::clone(&self.runtime);

    GLOBAL_RUNTIME
        .spawn(async move {
            let runtime = plugin_runtime.lock().await.take();
            if let Some(runtime) = runtime {
                runtime
                    .web_server
                    .shutdown()
                    .await
                    .map_err(|error| format!("failed to stop OPanel web server: {error}"))?;
            }

            info!("OPanel unloaded");
            Ok(())
        })
        .await
        .map_err(|error| format!("OPanel unload task failed: {error}"))?
}

#[plugin_impl]
struct OPanelPlugin {
    runtime: Arc<Mutex<Option<PluginRuntime>>>,
}

impl OPanelPlugin {
    fn new() -> Self {
        Self {
            runtime: Arc::new(Mutex::new(None)),
        }
    }
}
