// `plugin_impl` expands lifecycle methods through a second async layer.
#![allow(clippy::async_yields_async)]

use std::sync::Arc;

use pumpkin::plugin::Context;
use pumpkin_api_macros::{plugin_impl, plugin_method};
use tokio::sync::Mutex;
use tracing::info;

use crate::{config::OPanelConfig, opanel::OPanel, web::WebServer};

mod config;
mod event;
mod managers;
mod map;
mod monitor;
mod opanel;
mod storage;
mod task;
mod terminal;
mod utils;
mod web;

struct PluginRuntime {
    opanel: Arc<OPanel>,
    web_server: WebServer,
}

#[plugin_method]
async fn on_load(&self, context: Arc<Context>) -> Result<(), String> {
    let plugin_runtime = Arc::clone(&self.runtime);

    // Native plugins statically link their own Tokio state. Run all lifecycle work on the
    // runtime generated by `plugin_impl` so Tokio I/O can see the correct reactor.
    GLOBAL_RUNTIME
        .spawn(async move {
            context.init_log();

            if plugin_runtime.lock().await.is_some() {
                return Err("OPanel is already loaded".to_string());
            }

            let opanel = OPanel::initialize(context, OPanelConfig::default())
                .await
                .map_err(|error| error.to_string())?;
            let web_server = match WebServer::start(Arc::clone(&opanel)).await {
                Ok(web_server) => web_server,
                Err(error) => {
                    return match opanel.shutdown().await {
                        Ok(()) => Err(format!("failed to start OPanel web server: {error}")),
                        Err(shutdown_error) => Err(format!(
                            "failed to start OPanel web server: {error}; manager cleanup also failed: {shutdown_error}"
                        )),
                    };
                }
            };

            let mut runtime = plugin_runtime.lock().await;
            if runtime.is_some() {
                drop(runtime);
                shutdown_runtime(PluginRuntime {
                    opanel,
                    web_server,
                })
                .await
                .map_err(|error| {
                    format!("failed to stop duplicate OPanel web server: {error}")
                })?;
                return Err("OPanel is already loaded".to_string());
            }
            *runtime = Some(PluginRuntime {
                opanel,
                web_server,
            });

            info!("OPanel loaded");
            Ok(())
        })
        .await
        .map_err(|error| format!("OPanel load task failed: {error}"))?
}

#[plugin_method]
async fn on_unload(&self, _context: Arc<Context>) -> Result<(), String> {
    let plugin_runtime = Arc::clone(&self.runtime);

    GLOBAL_RUNTIME
        .spawn(async move {
            let runtime = plugin_runtime.lock().await.take();
            if let Some(runtime) = runtime {
                shutdown_runtime(runtime).await?;
            }

            info!("OPanel unloaded");
            Ok(())
        })
        .await
        .map_err(|error| format!("OPanel unload task failed: {error}"))?
}

async fn shutdown_runtime(runtime: PluginRuntime) -> Result<(), String> {
    let web_result = runtime.web_server.shutdown().await;
    let manager_result = runtime.opanel.shutdown().await;

    match (web_result, manager_result) {
        (Ok(()), Ok(())) => Ok(()),
        (Err(web_error), Ok(())) => Err(format!("failed to stop OPanel web server: {web_error}")),
        (Ok(()), Err(manager_error)) => {
            Err(format!("failed to stop OPanel managers: {manager_error}"))
        }
        (Err(web_error), Err(manager_error)) => Err(format!(
            "failed to stop OPanel web server: {web_error}; failed to stop OPanel managers: {manager_error}"
        )),
    }
}

#[plugin_impl]
struct OPanelPlugin {
    runtime: Arc<Mutex<Option<PluginRuntime>>>,
}

impl OPanelPlugin {
    fn new() -> Self {
        Self {
            runtime: Arc::new(Mutex::new(None)),
        }
    }
}
