name: Publish

on:
  workflow_dispatch:
  push:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Read version from gradle.properties
      id: read_version
      uses: christian-draeger/read-properties@1.1.1
      with:
        path: './gradle.properties'
        property: 'version'
    
    - name: Download release assets
      uses: robinraju/release-downloader@v1
      with:
        repository: "opanel-mc/opanel"
        tag: ${{ steps.version.outputs.value }}
        fileName: "*.jar"
        tarBall: false
        zipBall: false
        out-file-path: "release-jars"
    
    - uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: ${{ vars.MODRINTH_ID }}
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        files: "release-jars/*.jar"
        name: OPanel ${{ steps.version.outputs.value }}
        version: ${{ steps.version.outputs.value }}
        version-type: release
        loaders: |
          bukkit
          folia
          fabric
          forge
          neoforge
        game-versions: |
          [1.16.1,1.16.5]
          [1.19,1.21.9)
        java: |
          Java 14
          Java 17
          Java 21
